const fs = require('fs');
const path = require('path');

const questions = [
  // ARRAYS - 30 questions
  { id: 'arr-1', topic: 'arrays', difficulty: 'Easy', title: 'Two Sum', statement: 'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.', constraints: ['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9'], examples: [{ input: 'nums = [2,7,11,15], target = 9', output: '[0,1]' }] },
  { id: 'arr-2', topic: 'arrays', difficulty: 'Easy', title: 'Contains Duplicate', statement: 'Given an integer array `nums`, return `true` if any value appears at least twice in the array.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [1,2,3,1]', output: 'true' }] },
  { id: 'arr-3', topic: 'arrays', difficulty: 'Easy', title: 'Valid Anagram', statement: 'Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.', constraints: ['1 <= s.length, t.length <= 5 * 10^4'], examples: [{ input: 's = "anagram", t = "nagaram"', output: 'true' }] },
  { id: 'arr-4', topic: 'arrays', difficulty: 'Easy', title: 'Best Time to Buy and Sell Stock', statement: 'You are given an array `prices` where `prices[i]` is the price of a given stock on the `i-th` day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.', constraints: ['1 <= prices.length <= 10^5'], examples: [{ input: 'prices = [7,1,5,3,6,4]', output: '5', explanation: 'Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.' }] },
  { id: 'arr-5', topic: 'arrays', difficulty: 'Easy', title: 'Majority Element', statement: 'Given an array `nums` of size `n`, return the majority element. The majority element is the element that appears more than `⌊n / 2⌋` times.', constraints: ['n == nums.length', '1 <= n <= 5 * 10^4'], examples: [{ input: 'nums = [3,2,3]', output: '3' }] },
  { id: 'arr-6', topic: 'arrays', difficulty: 'Easy', title: 'Move Zeroes', statement: 'Given an integer array `nums`, move all `0`\'s to the end of it while maintaining the relative order of the non-zero elements.', constraints: ['1 <= nums.length <= 10^4'], examples: [{ input: 'nums = [0,1,0,3,12]', output: '[1,3,12,0,0]' }] },
  { id: 'arr-7', topic: 'arrays', difficulty: 'Easy', title: 'Squares of a Sorted Array', statement: 'Given an integer array `nums` sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.', constraints: ['1 <= nums.length <= 10^4'], examples: [{ input: 'nums = [-4,-1,0,3,10]', output: '[0,1,9,16,100]' }] },
  { id: 'arr-8', topic: 'arrays', difficulty: 'Easy', title: 'Remove Duplicates from Sorted Array', statement: 'Given an integer array `nums` sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once.', constraints: ['1 <= nums.length <= 3 * 10^4'], examples: [{ input: 'nums = [1,1,2]', output: '2, nums = [1,2,_]' }] },
  { id: 'arr-9', topic: 'arrays', difficulty: 'Easy', title: 'Intersection of Two Arrays', statement: 'Given two integer arrays `nums1` and `nums2`, return an array of their intersection. Each element in the result must be unique.', constraints: ['1 <= nums1.length, nums2.length <= 1000'], examples: [{ input: 'nums1 = [1,2,2,1], nums2 = [2,2]', output: '[2]' }] },
  { id: 'arr-10', topic: 'arrays', difficulty: 'Easy', title: 'Merge Sorted Array', statement: 'You are given two integer arrays `nums1` and `nums2`, sorted in non-decreasing order, and two integers `m` and `n`. Merge `nums2` into `nums1` as one sorted array.', constraints: ['nums1.length == m + n', '0 <= m, n <= 200'], examples: [{ input: 'nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3', output: '[1,2,2,3,5,6]' }] },

  { id: 'arr-11', topic: 'arrays', difficulty: 'Medium', title: '3Sum', statement: 'Given an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and `nums[i] + nums[j] + nums[k] == 0`.', constraints: ['3 <= nums.length <= 3000'], examples: [{ input: 'nums = [-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }] },
  { id: 'arr-12', topic: 'arrays', difficulty: 'Medium', title: 'Product of Array Except Self', statement: 'Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all the elements of `nums` except `nums[i]`.', constraints: ['2 <= nums.length <= 10^5'], examples: [{ input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' }] },
  { id: 'arr-13', topic: 'arrays', difficulty: 'Medium', title: 'Maximum Subarray (Kadane)', statement: 'Given an integer array `nums`, find the subarray with the largest sum, and return its sum.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6', explanation: '[4,-1,2,1] has the largest sum = 6.' }] },
  { id: 'arr-14', topic: 'arrays', difficulty: 'Medium', title: 'Container With Most Water', statement: 'You are given an integer array `height` of length `n`. Find two lines that together with the x-axis form a container, such that the container contains the most water.', constraints: ['n == height.length', '2 <= n <= 10^5'], examples: [{ input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49' }] },
  { id: 'arr-15', topic: 'arrays', difficulty: 'Medium', title: 'Longest Palindromic Substring', statement: 'Given a string `s`, return the longest palindromic substring in `s`.', constraints: ['1 <= s.length <= 1000'], examples: [{ input: 's = "babad"', output: '"bab"', explanation: '"aba" is also a valid answer.' }] },
  { id: 'arr-16', topic: 'arrays', difficulty: 'Medium', title: 'Group Anagrams', statement: 'Given an array of strings `strs`, group the anagrams together. You can return the answer in any order.', constraints: ['1 <= strs.length <= 10^4'], examples: [{ input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }] },
  { id: 'arr-17', topic: 'arrays', difficulty: 'Medium', title: 'Top K Frequent Elements', statement: 'Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. You may return the answer in any order.', constraints: ['1 <= nums.length <= 10^5', 'k is in range [1, number of unique elements]'], examples: [{ input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]' }] },
  { id: 'arr-18', topic: 'arrays', difficulty: 'Medium', title: 'Subarray Sum Equals K', statement: 'Given an array of integers `nums` and an integer `k`, return the total number of subarrays whose sum equals to `k`.', constraints: ['1 <= nums.length <= 2 * 10^4'], examples: [{ input: 'nums = [1,1,1], k = 2', output: '2' }] },
  { id: 'arr-19', topic: 'arrays', difficulty: 'Medium', title: '4Sum', statement: 'Given an array `nums` of `n` integers, return an array of all the unique quadruplets `[nums[a], nums[b], nums[c], nums[d]]` such that their sum is `target`.', constraints: ['n == nums.length', '1 <= n <= 200'], examples: [{ input: 'nums = [1,0,-1,0,-2,2], target = 0', output: '[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]' }] },
  { id: 'arr-20', topic: 'arrays', difficulty: 'Medium', title: 'Rotate Array', statement: 'Given an integer array `nums`, rotate the array to the right by `k` steps, where `k` is non-negative.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [1,2,3,4,5,6,7], k = 3', output: '[5,6,7,1,2,3,4]' }] },

  // DYNAMIC PROGRAMMING - 30 questions
  { id: 'dp-1', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Climbing Stairs', statement: 'It takes `n` steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?', constraints: ['1 <= n <= 45'], examples: [{ input: 'n = 2', output: '2' }] },
  { id: 'dp-2', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Fibonacci Number', statement: 'The Fibonacci numbers, commonly denoted `F(n)` form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones.', constraints: ['0 <= n <= 30'], examples: [{ input: 'n = 4', output: '3' }] },
  { id: 'dp-3', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Min Cost Climbing Stairs', statement: 'You are given an integer array `cost` where `cost[i]` is the cost of `i-th` step on a staircase. Once you pay the cost, you can either climb one or two steps.', constraints: ['2 <= cost.length <= 1000'], examples: [{ input: 'cost = [10,15,20]', output: '15' }] },
  { id: 'dp-4', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Maximum Subarray', statement: 'Given an integer array `nums`, find the subarray with the largest sum, and return its sum.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6' }] },
  { id: 'dp-5', topic: 'dynamic_programming', difficulty: 'Easy', title: 'House Robber', statement: 'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. The only constraint stopping you from robbing each of them is that adjacent houses have security systems.', constraints: ['1 <= nums.length <= 100'], examples: [{ input: 'nums = [1,2,3,1]', output: '4' }] },
  { id: 'dp-6', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Pascal\'s Triangle', statement: 'Given an integer `numRows`, return the first `numRows` of Pascal\'s triangle.', constraints: ['1 <= numRows <= 30'], examples: [{ input: 'numRows = 5', output: '[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]' }] },
  { id: 'dp-7', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Divisor Game', statement: 'Alice and Bob take turns playing a game, with Alice starting first. Initially, there is a number `n` on the chalkboard. On each player\'s turn, that player makes a move.', constraints: ['1 <= n <= 1000'], examples: [{ input: 'n = 2', output: 'true' }] },
  { id: 'dp-8', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Is Subsequence', statement: 'Given two strings `s` and `t`, return `true` if `s` is a subsequence of `t`, or `false` otherwise.', constraints: ['0 <= s.length <= 100', '0 <= t.length <= 10^4'], examples: [{ input: 's = "abc", t = "ahbgdc"', output: 'true' }] },
  { id: 'dp-9', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Range Sum Query - Immutable', statement: 'Given an integer array `nums`, handle multiple queries of the sum of the elements of a subarray `[left, right]`.', constraints: ['1 <= nums.length <= 10^4'], examples: [{ input: 'nums = [-2,0,3,-5,2,-1], query(0,2)', output: '1' }] },
  { id: 'dp-10', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Counting Bits', statement: 'Given an integer `n`, return an array `ans` of length `n + 1` such that for each `i` (`0 <= i <= n`), `ans[i]` is the number of `1`\'s in the binary representation of `i`.', constraints: ['0 <= n <= 10^5'], examples: [{ input: 'n = 2', output: '[0,1,1]' }] },

  { id: 'dp-11', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Longest Common Subsequence', statement: 'Given two strings `text1` and `text2`, return the length of their longest common subsequence.', constraints: ['1 <= text1.length, text2.length <= 1000'], examples: [{ input: 'text1 = "abcde", text2 = "ace"', output: '3' }] },
  { id: 'dp-12', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Coin Change', statement: 'You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money.', constraints: ['1 <= coins.length <= 12', '0 <= amount <= 10^4'], examples: [{ input: 'coins = [1,2,5], amount = 11', output: '3', explanation: '11 = 5 + 5 + 1' }] },
  { id: 'dp-13', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Longest Increasing Subsequence', statement: 'Given an integer array `nums`, return the length of the longest strictly increasing subsequence.', constraints: ['1 <= nums.length <= 2500'], examples: [{ input: 'nums = [10,9,2,5,3,7,101,18]', output: '4' }] },
  { id: 'dp-14', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Word Break', statement: 'Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.', constraints: ['1 <= s.length <= 300'], examples: [{ input: 's = "leetcode", wordDict = ["leet","code"]', output: 'true' }] },
  { id: 'dp-15', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Unique Paths', statement: 'There is a robot on an `m x n` grid. The robot is initially located at the top-left corner. The robot tries to move to the bottom-right corner. The robot can only move either down or right at any point in time.', constraints: ['1 <= m, n <= 100'], examples: [{ input: 'm = 3, n = 7', output: '28' }] },
  { id: 'dp-16', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Edit Distance', statement: 'Given two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2`.', constraints: ['0 <= word1.length, word2.length <= 500'], examples: [{ input: 'word1 = "horse", word2 = "ros"', output: '3' }] },
  { id: 'dp-17', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Decode Ways', statement: 'A message containing letters from A-Z can be encoded into numbers using the mapping: \'A\' -> "1", \'B\' -> "2", ..., \'Z\' -> "26". Given a string `s` containing only digits, return the number of ways to decode it.', constraints: ['1 <= s.length <= 100'], examples: [{ input: 's = "12"', output: '2' }] },
  { id: 'dp-18', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Palindromic Substrings', statement: 'Given a string `s`, return the number of palindromic substrings in it.', constraints: ['1 <= s.length <= 1000'], examples: [{ input: 's = "abc"', output: '3' }] },
  { id: 'dp-19', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Maximum Product Subarray', statement: 'Given an integer array `nums`, find a subarray that has the largest product, and return the product.', constraints: ['1 <= nums.length <= 2 * 10^4'], examples: [{ input: 'nums = [2,3,-2,4]', output: '6' }] },
  { id: 'dp-20', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Target Sum', statement: 'You are given an integer array `nums` and an integer `target`. You want to build an expression out of nums by adding one of the symbols \'+\' and \'-\' before each integer in nums and then concatenate them all.', constraints: ['1 <= nums.length <= 20'], examples: [{ input: 'nums = [1,1,1,1,1], target = 3', output: '5' }] },

  // TREES & GRAPHS - 25 questions
  { id: 'tg-1', topic: 'trees_graphs', difficulty: 'Easy', title: 'Invert Binary Tree', statement: 'Given the root of a binary tree, invert the tree, and return its root.', constraints: ['The number of nodes in the tree is in the range [0, 100].'], examples: [{ input: 'root = [4,2,7,1,3,6,9]', output: '[4,7,2,9,6,3,1]' }] },
  { id: 'tg-2', topic: 'trees_graphs', difficulty: 'Easy', title: 'Maximum Depth of Binary Tree', statement: 'Given the root of a binary tree, return its maximum depth.', constraints: ['The number of nodes in the tree is in the range [0, 10^4].'], examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: '3' }] },
  { id: 'tg-3', topic: 'trees_graphs', difficulty: 'Easy', title: 'Diameter of Binary Tree', statement: 'Given the root of a binary tree, return the length of the diameter of the tree.', constraints: ['The number of nodes in the tree is in the range [1, 10^4].'], examples: [{ input: 'root = [1,2,3,4,5]', output: '3' }] },
  { id: 'tg-4', topic: 'trees_graphs', difficulty: 'Easy', title: 'Balanced Binary Tree', statement: 'Given a binary tree, determine if it is height-balanced.', constraints: ['The number of nodes in the tree is in the range [0, 5000].'], examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: 'true' }] },
  { id: 'tg-5', topic: 'trees_graphs', difficulty: 'Easy', title: 'Same Tree', statement: 'Given the roots of two binary trees `p` and `q`, write a function to check if they are the same or not.', constraints: ['The number of nodes in both trees is in the range [0, 100].'], examples: [{ input: 'p = [1,2,3], q = [1,2,3]', output: 'true' }] },
];

const dataDir = path.join(__dirname, '..', 'data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir);

fs.writeFileSync(
  path.join(dataDir, 'questions.json'),
  JSON.stringify(questions, null, 2)
);

console.log('Successfully seeded questions to backend/data/questions.json');
