const fs = require('fs');
const path = require('path');

const questions = [
  // ARRAYS - 30 questions
  { id: 'arr-1', topic: 'arrays', difficulty: 'Easy', title: 'Two Sum', statement: 'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.', constraints: ['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9'], examples: [{ input: 'nums = [2,7,11,15], target = 9', output: '[0,1]' }] },
  { id: 'arr-2', topic: 'arrays', difficulty: 'Easy', title: 'Contains Duplicate', statement: 'Given an integer array `nums`, return `true` if any value appears at least twice in the array.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [1,2,3,1]', output: 'true' }] },
  { id: 'arr-3', topic: 'arrays', difficulty: 'Easy', title: 'Valid Anagram', statement: 'Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.', constraints: ['1 <= s.length, t.length <= 5 * 10^4'], examples: [{ input: 's = "anagram", t = "nagaram"', output: 'true' }] },
  { id: 'arr-4', topic: 'arrays', difficulty: 'Easy', title: 'Best Time to Buy and Sell Stock', statement: 'You are given an array `prices` where `prices[i]` is the price of a given stock on the `i-th` day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.', constraints: ['1 <= prices.length <= 10^5'], examples: [{ input: 'prices = [7,1,5,3,6,4]', output: '5', explanation: 'Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.' }] },
  { id: 'arr-5', topic: 'arrays', difficulty: 'Easy', title: 'Majority Element', statement: 'Given an array `nums` of size `n`, return the majority element. The majority element is the element that appears more than `⌊n / 2⌋` times.', constraints: ['n == nums.length', '1 <= n <= 5 * 10^4'], examples: [{ input: 'nums = [3,2,3]', output: '3' }] },
  { id: 'arr-6', topic: 'arrays', difficulty: 'Easy', title: 'Move Zeroes', statement: 'Given an integer array `nums`, move all `0`\'s to the end of it while maintaining the relative order of the non-zero elements.', constraints: ['1 <= nums.length <= 10^4'], examples: [{ input: 'nums = [0,1,0,3,12]', output: '[1,3,12,0,0]' }] },
  { id: 'arr-7', topic: 'arrays', difficulty: 'Easy', title: 'Squares of a Sorted Array', statement: 'Given an integer array `nums` sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.', constraints: ['1 <= nums.length <= 10^4'], examples: [{ input: 'nums = [-4,-1,0,3,10]', output: '[0,1,9,16,100]' }] },
  { id: 'arr-8', topic: 'arrays', difficulty: 'Easy', title: 'Remove Duplicates from Sorted Array', statement: 'Given an integer array `nums` sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once.', constraints: ['1 <= nums.length <= 3 * 10^4'], examples: [{ input: 'nums = [1,1,2]', output: '2, nums = [1,2,_]' }] },
  { id: 'arr-9', topic: 'arrays', difficulty: 'Easy', title: 'Intersection of Two Arrays', statement: 'Given two integer arrays `nums1` and `nums2`, return an array of their intersection. Each element in the result must be unique.', constraints: ['1 <= nums1.length, nums2.length <= 1000'], examples: [{ input: 'nums1 = [1,2,2,1], nums2 = [2,2]', output: '[2]' }] },
  { id: 'arr-10', topic: 'arrays', difficulty: 'Easy', title: 'Merge Sorted Array', statement: 'You are given two integer arrays `nums1` and `nums2`, sorted in non-decreasing order, and two integers `m` and `n`. Merge `nums2` into `nums1` as one sorted array.', constraints: ['nums1.length == m + n', '0 <= m, n <= 200'], examples: [{ input: 'nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3', output: '[1,2,2,3,5,6]' }] },

  { id: 'arr-11', topic: 'arrays', difficulty: 'Medium', title: '3Sum', statement: 'Given an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and `nums[i] + nums[j] + nums[k] == 0`.', constraints: ['3 <= nums.length <= 3000'], examples: [{ input: 'nums = [-1,0,1,2,-1,-4]', output: '[[-1,-1,2],[-1,0,1]]' }] },
  { id: 'arr-12', topic: 'arrays', difficulty: 'Medium', title: 'Product of Array Except Self', statement: 'Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all the elements of `nums` except `nums[i]`.', constraints: ['2 <= nums.length <= 10^5'], examples: [{ input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' }] },
  { id: 'arr-13', topic: 'arrays', difficulty: 'Medium', title: 'Maximum Subarray (Kadane)', statement: 'Given an integer array `nums`, find the subarray with the largest sum, and return its sum.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6', explanation: '[4,-1,2,1] has the largest sum = 6.' }] },
  { id: 'arr-14', topic: 'arrays', difficulty: 'Medium', title: 'Container With Most Water', statement: 'You are given an integer array `height` of length `n`. Find two lines that together with the x-axis form a container, such that the container contains the most water.', constraints: ['n == height.length', '2 <= n <= 10^5'], examples: [{ input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49' }] },
  { id: 'arr-15', topic: 'arrays', difficulty: 'Medium', title: 'Longest Palindromic Substring', statement: 'Given a string `s`, return the longest palindromic substring in `s`.', constraints: ['1 <= s.length <= 1000'], examples: [{ input: 's = "babad"', output: '"bab"', explanation: '"aba" is also a valid answer.' }] },
  { id: 'arr-16', topic: 'arrays', difficulty: 'Medium', title: 'Group Anagrams', statement: 'Given an array of strings `strs`, group the anagrams together. You can return the answer in any order.', constraints: ['1 <= strs.length <= 10^4'], examples: [{ input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' }] },
  { id: 'arr-17', topic: 'arrays', difficulty: 'Medium', title: 'Top K Frequent Elements', statement: 'Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. You may return the answer in any order.', constraints: ['1 <= nums.length <= 10^5', 'k is in range [1, number of unique elements]'], examples: [{ input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]' }] },
  { id: 'arr-18', topic: 'arrays', difficulty: 'Medium', title: 'Subarray Sum Equals K', statement: 'Given an array of integers `nums` and an integer `k`, return the total number of subarrays whose sum equals to `k`.', constraints: ['1 <= nums.length <= 2 * 10^4'], examples: [{ input: 'nums = [1,1,1], k = 2', output: '2' }] },
  { id: 'arr-19', topic: 'arrays', difficulty: 'Medium', title: '4Sum', statement: 'Given an array `nums` of `n` integers, return an array of all the unique quadruplets `[nums[a], nums[b], nums[c], nums[d]]` such that their sum is `target`.', constraints: ['n == nums.length', '1 <= n <= 200'], examples: [{ input: 'nums = [1,0,-1,0,-2,2], target = 0', output: '[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]' }] },
  { id: 'arr-20', topic: 'arrays', difficulty: 'Medium', title: 'Rotate Array', statement: 'Given an integer array `nums`, rotate the array to the right by `k` steps, where `k` is non-negative.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [1,2,3,4,5,6,7], k = 3', output: '[5,6,7,1,2,3,4]' }] },

  { id: 'arr-21', topic: 'arrays', difficulty: 'Hard', title: 'Median of Two Sorted Arrays', statement: 'Given two sorted arrays `nums1` and `nums2` of size `m` and `n` respectively, return the median of the two sorted arrays.', constraints: ['nums1.length == m', 'nums2.length == n', '0 <= m, n <= 1000', '1 <= m + n <= 2000'], examples: [{ input: 'nums1 = [1,3], nums2 = [2]', output: '2.00000' }] },
  { id: 'arr-22', topic: 'arrays', difficulty: 'Hard', title: 'Trapping Rain Water', statement: 'Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.', constraints: ['n == height.length', '1 <= n <= 2 * 10^4'], examples: [{ input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' }] },
  { id: 'arr-23', topic: 'arrays', difficulty: 'Hard', title: 'First Missing Positive', statement: 'Given an unsorted integer array `nums`, return the smallest missing positive integer.', constraints: ['1 <= nums.length <= 5 * 10^5'], examples: [{ input: 'nums = [1,2,0]', output: '3' }] },
  { id: 'arr-24', topic: 'arrays', difficulty: 'Hard', title: 'Longest Valid Parentheses', statement: 'Given a string containing just the characters \'(\' and \')\', return the length of the longest valid (well-formed) parentheses substring.', constraints: ['0 <= s.length <= 3 * 10^4'], examples: [{ input: 's = ")()())"', output: '4' }] },
  { id: 'arr-25', topic: 'arrays', difficulty: 'Hard', title: 'Sliding Window Maximum', statement: 'You are given an array of integers `nums`, there is a sliding window of size `k` which is moving from the very left of the array to the very right. Return the max sliding window.', constraints: ['1 <= nums.length <= 10^5', '1 <= k <= nums.length'], examples: [{ input: 'nums = [1,3,-1,-3,5,3,6,7], k = 3', output: '[3,3,5,5,6,7]' }] },
  { id: 'arr-26', topic: 'arrays', difficulty: 'Hard', title: 'Minimum Window Substring', statement: 'Given two strings `s` and `t`, return the minimum window substring of `s` such that every character in `t` (including duplicates) is included in the window.', constraints: ['m == s.length, n == t.length', '1 <= m, n <= 10^5'], examples: [{ input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' }] },
  { id: 'arr-27', topic: 'arrays', difficulty: 'Hard', title: 'Wildcard Matching', statement: 'Given an input string (`s`) and a pattern (`p`), implement wildcard pattern matching with support for \'?\' and \'*\' where \'?\' matches any single character and \'*\' matches any sequence of characters.', constraints: ['0 <= s.length, p.length <= 2000'], examples: [{ input: 's = "aa", p = "*"', output: 'true' }] },
  { id: 'arr-28', topic: 'arrays', difficulty: 'Hard', title: 'Reverse Nodes in k-Group', statement: 'Given the head of a linked list, reverse the nodes of the list `k` at a time and return its modified list.', constraints: ['The number of nodes in the list is n.', '1 <= k <= n <= 5000'], examples: [{ input: 'head = [1,2,3,4,5], k = 2', output: '[2,1,4,3,5]' }] },
  { id: 'arr-29', topic: 'arrays', difficulty: 'Hard', title: 'Sudoku Solver', statement: 'Write a program to solve a Sudoku puzzle by filling the empty cells.', constraints: ['board.length == 9', 'board[i].length == 9'], examples: [{ input: 'board = [["5","3",".",...]]', output: 'board filled' }] },
  { id: 'arr-30', topic: 'arrays', difficulty: 'Hard', title: 'Merge k Sorted Lists', statement: 'You are given an array of `k` linked-lists `lists`, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.', constraints: ['k == lists.length', '0 <= k <= 10^4', '0 <= lists[i].length <= 500'], examples: [{ input: 'lists = [[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' }] },

  // DYNAMIC PROGRAMMING - 30 questions
  { id: 'dp-1', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Climbing Stairs', statement: 'It takes `n` steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?', constraints: ['1 <= n <= 45'], examples: [{ input: 'n = 2', output: '2' }] },
  { id: 'dp-2', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Fibonacci Number', statement: 'The Fibonacci numbers, commonly denoted `F(n)` form a sequence, called the Fibonacci sequence, such that each number is the sum of the two preceding ones.', constraints: ['0 <= n <= 30'], examples: [{ input: 'n = 4', output: '3' }] },
  { id: 'dp-3', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Min Cost Climbing Stairs', statement: 'You are given an integer array `cost` where `cost[i]` is the cost of `i-th` step on a staircase. Once you pay the cost, you can either climb one or two steps.', constraints: ['2 <= cost.length <= 1000'], examples: [{ input: 'cost = [10,15,20]', output: '15' }] },
  { id: 'dp-4', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Maximum Subarray', statement: 'Given an integer array `nums`, find the subarray with the largest sum, and return its sum.', constraints: ['1 <= nums.length <= 10^5'], examples: [{ input: 'nums = [-2,1,-3,4,-1,2,1,-5,4]', output: '6' }] },
  { id: 'dp-5', topic: 'dynamic_programming', difficulty: 'Easy', title: 'House Robber', statement: 'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. The only constraint stopping you from robbing each of them is that adjacent houses have security systems.', constraints: ['1 <= nums.length <= 100'], examples: [{ input: 'nums = [1,2,3,1]', output: '4' }] },
  { id: 'dp-6', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Pascal\'s Triangle', statement: 'Given an integer `numRows`, return the first `numRows` of Pascal\'s triangle.', constraints: ['1 <= numRows <= 30'], examples: [{ input: 'numRows = 5', output: '[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]' }] },
  { id: 'dp-7', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Divisor Game', statement: 'Alice and Bob take turns playing a game, with Alice starting first. Initially, there is a number `n` on the chalkboard. On each player\'s turn, that player makes a move.', constraints: ['1 <= n <= 1000'], examples: [{ input: 'n = 2', output: 'true' }] },
  { id: 'dp-8', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Is Subsequence', statement: 'Given two strings `s` and `t`, return `true` if `s` is a subsequence of `t`, or `false` otherwise.', constraints: ['0 <= s.length <= 100', '0 <= t.length <= 10^4'], examples: [{ input: 's = "abc", t = "ahbgdc"', output: 'true' }] },
  { id: 'dp-9', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Range Sum Query - Immutable', statement: 'Given an integer array `nums`, handle multiple queries of the sum of the elements of a subarray `[left, right]`.', constraints: ['1 <= nums.length <= 10^4'], examples: [{ input: 'nums = [-2,0,3,-5,2,-1], query(0,2)', output: '1' }] },
  { id: 'dp-10', topic: 'dynamic_programming', difficulty: 'Easy', title: 'Counting Bits', statement: 'Given an integer `n`, return an array `ans` of length `n + 1` such that for each `i` (`0 <= i <= n`), `ans[i]` is the number of `1`\'s in the binary representation of `i`.', constraints: ['0 <= n <= 10^5'], examples: [{ input: 'n = 2', output: '[0,1,1]' }] },

  { id: 'dp-11', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Longest Common Subsequence', statement: 'Given two strings `text1` and `text2`, return the length of their longest common subsequence.', constraints: ['1 <= text1.length, text2.length <= 1000'], examples: [{ input: 'text1 = "abcde", text2 = "ace"', output: '3' }] },
  { id: 'dp-12', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Coin Change', statement: 'You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money.', constraints: ['1 <= coins.length <= 12', '0 <= amount <= 10^4'], examples: [{ input: 'coins = [1,2,5], amount = 11', output: '3', explanation: '11 = 5 + 5 + 1' }] },
  { id: 'dp-13', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Longest Increasing Subsequence', statement: 'Given an integer array `nums`, return the length of the longest strictly increasing subsequence.', constraints: ['1 <= nums.length <= 2500'], examples: [{ input: 'nums = [10,9,2,5,3,7,101,18]', output: '4' }] },
  { id: 'dp-14', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Word Break', statement: 'Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.', constraints: ['1 <= s.length <= 300'], examples: [{ input: 's = "leetcode", wordDict = ["leet","code"]', output: 'true' }] },
  { id: 'dp-15', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Unique Paths', statement: 'There is a robot on an `m x n` grid. The robot is initially located at the top-left corner. The robot tries to move to the bottom-right corner. The robot can only move either down or right at any point in time.', constraints: ['1 <= m, n <= 100'], examples: [{ input: 'm = 3, n = 7', output: '28' }] },
  { id: 'dp-16', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Edit Distance', statement: 'Given two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2`.', constraints: ['0 <= word1.length, word2.length <= 500'], examples: [{ input: 'word1 = "horse", word2 = "ros"', output: '3' }] },
  { id: 'dp-17', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Decode Ways', statement: 'A message containing letters from A-Z can be encoded into numbers using the mapping: \'A\' -> "1", \'B\' -> "2", ..., \'Z\' -> "26". Given a string `s` containing only digits, return the number of ways to decode it.', constraints: ['1 <= s.length <= 100'], examples: [{ input: 's = "12"', output: '2' }] },
  { id: 'dp-18', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Palindromic Substrings', statement: 'Given a string `s`, return the number of palindromic substrings in it.', constraints: ['1 <= s.length <= 1000'], examples: [{ input: 's = "abc"', output: '3' }] },
  { id: 'dp-19', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Maximum Product Subarray', statement: 'Given an integer array `nums`, find a subarray that has the largest product, and return the product.', constraints: ['1 <= nums.length <= 2 * 10^4'], examples: [{ input: 'nums = [2,3,-2,4]', output: '6' }] },
  { id: 'dp-20', topic: 'dynamic_programming', difficulty: 'Medium', title: 'Target Sum', statement: 'You are given an integer array `nums` and an integer `target`. You want to build an expression out of nums by adding one of the symbols \'+\' and \'-\' before each integer in nums and then concatenate them all.', constraints: ['1 <= nums.length <= 20'], examples: [{ input: 'nums = [1,1,1,1,1], target = 3', output: '5' }] },

  { id: 'dp-21', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Regular Expression Matching', statement: 'Given an input string (`s`) and a pattern (`p`), implement regular expression matching with support for \'.\' and \'*\' where \'.\' matches any single character and \'*\' matches zero or more of the preceding element.', constraints: ['1 <= s.length <= 20', '1 <= p.length <= 30'], examples: [{ input: 's = "aa", p = "a*"', output: 'true' }] },
  { id: 'dp-22', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Longest Valid Parentheses', statement: 'Given a string containing just the characters \'(\' and \')\', return the length of the longest valid (well-formed) parentheses substring.', constraints: ['0 <= s.length <= 3 * 10^4'], examples: [{ input: 's = "(()"', output: '2' }] },
  { id: 'dp-23', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Distinct Subsequences', statement: 'Given two strings `s` and `t`, return the number of distinct subsequences of `s` which equals `t`.', constraints: ['1 <= s.length, t.length <= 1000'], examples: [{ input: 's = "rabbbit", t = "rabbit"', output: '3' }] },
  { id: 'dp-24', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Burst Balloons', statement: 'You are given `n` balloons, indexed from 0 to `n - 1`. Each balloon is painted with a number on it, represented by an array `nums`. If you burst the ith balloon, you will get `nums[i - 1] * nums[i] * nums[i + 1]` coins.', constraints: ['1 <= n <= 300'], examples: [{ input: 'nums = [3,1,5,8]', output: '167' }] },
  { id: 'dp-25', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Scramble String', statement: 'We can scramble a string `s` to get a string `t` using a specific recursive algorithm.', constraints: ['s.length == t.length', '1 <= s.length <= 30'], examples: [{ input: 's1 = "great", s2 = "rgeat"', output: 'true' }] },
  { id: 'dp-26', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Interleaving String', statement: 'Given strings `s1`, `s2`, and `s3`, find whether `s3` is formed by an interleaving of `s1` and `s2`.', constraints: ['0 <= s1.length, s2.length <= 100', '0 <= s3.length <= 200'], examples: [{ input: 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac"', output: 'true' }] },
  { id: 'dp-27', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Super Egg Drop', statement: 'You are given `k` identical eggs and you have access to a building with `n` floors labeled from 1 to `n`. Find the minimum number of moves that you need to make to determine with certainty what the highest floor `f` is.', constraints: ['1 <= k <= 100', '1 <= n <= 10^4'], examples: [{ input: 'k = 1, n = 2', output: '2' }] },
  { id: 'dp-28', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Best Time to Buy and Sell Stock IV', statement: 'You are given an integer array `prices` where `prices[i]` is the price of a given stock on the `i-th` day, and an integer `k`. Find the maximum profit you can achieve. You may complete at most `k` transactions.', constraints: ['1 <= prices.length <= 1000', '0 <= k <= 100'], examples: [{ input: 'k = 2, prices = [3,2,6,5,0,3]', output: '7' }] },
  { id: 'dp-29', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Dungeon Game', statement: 'The demons had captured the princess and imprisoned her in the bottom-right corner of a dungeon. The dungeon consists of `m x n` rooms.', constraints: ['m == dungeon.length', 'n == dungeon[i].length', '1 <= m, n <= 200'], examples: [{ input: 'dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]]', output: '7' }] },
  { id: 'dp-30', topic: 'dynamic_programming', difficulty: 'Hard', title: 'Word Wrap Problem', statement: 'Given a sequence of words, and a limit on the number of characters that can be put in one line (line width). Put line breaks in the given sequence such that the lines are printed neatly.', constraints: ['words.length <= 500', 'lineWidth <= 50'], examples: [{ input: 'words = ["Geeks", "for", "Geeks", "presents", "word", "wrap", "problem"], width = 15', output: 'cost' }] },

  // TREES & GRAPHS - 25 questions
  { id: 'tg-1', topic: 'trees_graphs', difficulty: 'Easy', title: 'Invert Binary Tree', statement: 'Given the root of a binary tree, invert the tree, and return its root.', constraints: ['The number of nodes in the tree is in the range [0, 100].'], examples: [{ input: 'root = [4,2,7,1,3,6,9]', output: '[4,7,2,9,6,3,1]' }] },
  { id: 'tg-2', topic: 'trees_graphs', difficulty: 'Easy', title: 'Maximum Depth of Binary Tree', statement: 'Given the root of a binary tree, return its maximum depth.', constraints: ['The number of nodes in the tree is in the range [0, 10^4].'], examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: '3' }] },
  { id: 'tg-3', topic: 'trees_graphs', difficulty: 'Easy', title: 'Diameter of Binary Tree', statement: 'Given the root of a binary tree, return the length of the diameter of the tree.', constraints: ['The number of nodes in the tree is in the range [1, 10^4].'], examples: [{ input: 'root = [1,2,3,4,5]', output: '3' }] },
  { id: 'tg-4', topic: 'trees_graphs', difficulty: 'Easy', title: 'Balanced Binary Tree', statement: 'Given a binary tree, determine if it is height-balanced.', constraints: ['The number of nodes in the tree is in the range [0, 5000].'], examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: 'true' }] },
  { id: 'tg-5', topic: 'trees_graphs', difficulty: 'Easy', title: 'Same Tree', statement: 'Given the roots of two binary trees `p` and `q`, write a function to check if they are the same or not.', constraints: ['The number of nodes in both trees is in the range [0, 100].'], examples: [{ input: 'p = [1,2,3], q = [1,2,3]', output: 'true' }] },
  { id: 'tg-6', topic: 'trees_graphs', difficulty: 'Medium', title: 'Binary Tree Level Order Traversal', statement: 'Given the root of a binary tree, return the level order traversal of its nodes\' values. (i.e., from left to right, level by level).', constraints: ['The number of nodes in the tree is in the range [0, 2000].'], examples: [{ input: 'root = [3,9,20,null,null,15,7]', output: '[[3],[9,20],[15,7]]' }] },
  { id: 'tg-7', topic: 'trees_graphs', difficulty: 'Medium', title: 'Lowest Common Ancestor of a Binary Tree', statement: 'Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.', constraints: ['The number of nodes in the tree is in the range [2, 10^5].'], examples: [{ input: 'root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1', output: '3' }] },
  { id: 'tg-8', topic: 'trees_graphs', difficulty: 'Medium', title: 'Binary Tree Right Side View', statement: 'Given the root of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.', constraints: ['The number of nodes in the tree is in the range [0, 100].'], examples: [{ input: 'root = [1,2,3,null,5,null,4]', output: '[1,3,4]' }] },
  { id: 'tg-9', topic: 'trees_graphs', difficulty: 'Medium', title: 'Number of Islands', statement: 'Given an `m x n` 2D binary grid which represents a map of \'1\'s (land) and \'0\'s (water), return the number of islands.', constraints: ['m == grid.length', 'n == grid[i].length', '1 <= m, n <= 300'], examples: [{ input: 'grid = [["1","1","1","1","0"],...]', output: '1' }] },
  { id: 'tg-10', topic: 'trees_graphs', difficulty: 'Medium', title: 'Course Schedule', statement: 'There are a total of `numCourses` courses you have to take, labeled from 0 to `numCourses - 1`. Check if you can finish all courses.', constraints: ['1 <= numCourses <= 2000'], examples: [{ input: 'numCourses = 2, prerequisites = [[1,0]]', output: 'true' }] },
  { id: 'tg-11', topic: 'trees_graphs', difficulty: 'Medium', title: 'Clone Graph', statement: 'Given a reference of a node in a connected undirected graph. Return a deep copy (clone) of the graph.', constraints: ['The number of nodes in the graph is in the range [0, 100].'], examples: [{ input: 'adjList = [[2,4],[1,3],[2,4],[1,3]]', output: '[[2,4],[1,3],[2,4],[1,3]]' }] },
  { id: 'tg-12', topic: 'trees_graphs', difficulty: 'Medium', title: 'Pacific Atlantic Water Flow', statement: 'There is an `m x n` rectangular island that borders both the Pacific Ocean and Atlantic Ocean.', constraints: ['m == heights.length', 'n == heights[r].length'], examples: [{ input: 'heights = [[1,2,2,3,5],...]', output: '[[0,4],[1,3],...]' }] },
  { id: 'tg-13', topic: 'trees_graphs', difficulty: 'Hard', title: 'Word Ladder', statement: 'A transformation sequence from word `beginWord` to word `endWord` using a dictionary `wordList`. Return the number of words in the shortest transformation sequence.', constraints: ['1 <= beginWord.length <= 10'], examples: [{ input: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]', output: '5' }] },
  { id: 'tg-14', topic: 'trees_graphs', difficulty: 'Hard', title: 'Binary Tree Maximum Path Sum', statement: 'A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. Find the maximum path sum.', constraints: ['The number of nodes in the tree is in the range [1, 3 * 10^4].'], examples: [{ input: 'root = [-10,9,20,null,null,15,7]', output: '42' }] },
  { id: 'tg-15', topic: 'trees_graphs', difficulty: 'Hard', title: 'Longest Increasing Path in a Matrix', statement: 'Given an `m x n` integers matrix, return the length of the longest increasing path in matrix.', constraints: ['m == matrix.length', 'n == matrix[i].length'], examples: [{ input: 'matrix = [[9,9,4],[6,6,8],[2,1,1]]', output: '4' }] },
  { id: 'tg-16', topic: 'trees_graphs', difficulty: 'Medium', title: 'Rotting Oranges', statement: 'You are given an `m x n` grid where each cell can have one of three values: 0 (empty), 1 (fresh), 2 (rotten). Return the minimum time until no fresh orange remains.', constraints: ['m == grid.length', 'n == grid[i].length'], examples: [{ input: 'grid = [[2,1,1],[1,1,0],[0,1,1]]', output: '4' }] },
  { id: 'tg-17', topic: 'trees_graphs', difficulty: 'Medium', title: 'Network Delay Time', statement: 'You are given a network of `n` nodes, labeled from 1 to `n`. You are also given `times`, a list of travel times as directed edges. Return the time it takes for all nodes to receive the signal.', constraints: ['1 <= n <= 100'], examples: [{ input: 'times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2', output: '2' }] },
  { id: 'tg-18', topic: 'trees_graphs', difficulty: 'Hard', title: 'Alien Dictionary', statement: 'There is a new alien language that uses the English alphabet. However, the order of the letters is unknown to you. Derive the order.', constraints: ['1 <= words.length <= 100'], examples: [{ input: 'words = ["wrt","wrf","er","ett","rftt"]', output: '"wertf"' }] },
  { id: 'tg-19', topic: 'trees_graphs', difficulty: 'Medium', title: 'Kth Smallest Element in a BST', statement: 'Given the root of a binary search tree, and an integer `k`, return the `k-th` smallest value (1-indexed) of all the values of the nodes in the tree.', constraints: ['The number of nodes in the tree is n.'], examples: [{ input: 'root = [3,1,4,null,2], k = 1', output: '1' }] },
  { id: 'tg-20', topic: 'trees_graphs', difficulty: 'Hard', title: 'Serialize and Deserialize Binary Tree', statement: 'Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work.', constraints: ['The number of nodes in the tree is in the range [0, 10^4].'], examples: [{ input: 'root = [1,2,3,null,null,4,5]', output: '[1,2,3,null,null,4,5]' }] },
  { id: 'tg-21', topic: 'trees_graphs', difficulty: 'Medium', title: 'Validate Binary Search Tree', statement: 'Given the root of a binary tree, determine if it is a valid binary search tree (BST).', constraints: ['The number of nodes in the tree is in the range [1, 10^4].'], examples: [{ input: 'root = [2,1,3]', output: 'true' }] },
  { id: 'tg-22', topic: 'trees_graphs', difficulty: 'Medium', title: 'Populating Next Right Pointers in Each Node', statement: 'You are given a perfect binary tree where all leaves are on the same level, and every parent has two children. Populate each next pointer.', constraints: ['The number of nodes in the tree is in the range [0, 4096].'], examples: [{ input: 'root = [1,2,3,4,5,6,7]', output: '[1,#,2,3,#,4,5,6,7,#]' }] },
  { id: 'tg-23', topic: 'trees_graphs', difficulty: 'Medium', title: 'Redundant Connection', statement: 'In this problem, a tree is an undirected graph that is connected and has no cycles. Return an edge that can be removed so that the resulting graph is a tree.', constraints: ['n == edges.length', '3 <= n <= 1000'], examples: [{ input: 'edges = [[1,2],[1,3],[2,3]]', output: '[2,3]' }] },
  { id: 'tg-24', topic: 'trees_graphs', difficulty: 'Hard', title: 'Critical Connections in a Network', statement: 'There are `n` servers numbered from 0 to `n - 1` connected by undirected server-to-server connections forming a network. Return all critical connections.', constraints: ['2 <= n <= 10^5'], examples: [{ input: 'n = 4, connections = [[0,1],[1,2],[2,0],[1,3]]', output: '[[1,3]]' }] },
  { id: 'tg-25', topic: 'trees_graphs', difficulty: 'Medium', title: 'Path Sum III', statement: 'Given the root of a binary tree and an integer `targetSum`, return the number of paths where the sum of the values along the path equals `targetSum`.', constraints: ['The number of nodes in the tree is in the range [0, 1000].'], examples: [{ input: 'root = [10,5,-3,3,2,null,11,3,-2,null,1], targetSum = 8', output: '3' }] },

  // SYSTEM DESIGN - 15 questions
  { id: 'sd-1', topic: 'system_design', difficulty: 'Hard', title: 'Design URL Shortener (TinyURL)', statement: 'Design a service like TinyURL. It should be able to shorten a long URL and redirect users to the original URL when the short URL is accessed.', constraints: ['100M URLs per month', 'High availability', 'Low latency'], examples: [{ input: 'URL: google.com', output: 'bit.ly/abcd123' }] },
  { id: 'sd-2', topic: 'system_design', difficulty: 'Hard', title: 'Design WhatsApp/Messenger', statement: 'Design a real-time messaging service that supports one-on-one chat, group chat, and online/offline status.', constraints: ['Billions of users', 'Real-time delivery', 'Message persistence'], examples: [{ input: 'User A sends message to User B', output: 'User B receives notification immediately' }] },
  { id: 'sd-3', topic: 'system_design', difficulty: 'Hard', title: 'Design YouTube/Netflix', statement: 'Design a video streaming platform that supports video uploads, processing, and streaming across different devices and bandwidths.', constraints: ['High throughput', 'Content Delivery Network (CDN)', 'Latency sensitivity'], examples: [{ input: 'Video upload 1080p', output: 'Available in 144p, 360p, 720p, 1080p' }] },
  { id: 'sd-4', topic: 'system_design', difficulty: 'Hard', title: 'Design Uber/Lyft', statement: 'Design a ride-sharing service that connects passengers with nearby drivers in real-time.', constraints: ['Geospatial indexing', 'Real-time tracking', 'Surge pricing logic'], examples: [{ input: 'Passenger requests ride at (x,y)', output: 'Nearest driver notified' }] },
  { id: 'sd-5', topic: 'system_design', difficulty: 'Hard', title: 'Design Twitter/X Feed', statement: 'Design a social media feed system (Timeline) where users can see tweets from people they follow in chronological order.', constraints: ['High read volume', 'Fan-out on write/load', 'Real-time updates'], examples: [{ input: 'User tweets', output: 'Followers see it in their feed' }] },
  { id: 'sd-6', topic: 'system_design', difficulty: 'Hard', title: 'Design Instagram', statement: 'Design a photo-sharing app that supports image uploads, filters, news feeds, and follows.', constraints: ['Large scale image storage', 'Efficient feed generation', 'Search functionality'], examples: [{ input: 'Upload photo', output: 'Rendered in followers\' feeds' }] },
  { id: 'sd-7', topic: 'system_design', difficulty: 'Hard', title: 'Design Web Crawler', statement: 'Design a system that crawls the entire web to index pages for a search engine.', constraints: ['Politeness policy', 'Duplicate detection', 'Distributed crawling'], examples: [{ input: 'Seed URL: google.com', output: 'Billions of indexed pages' }] },
  { id: 'sd-8', topic: 'system_design', difficulty: 'Hard', title: 'Design Rate Limiter', statement: 'Design a service to limit the number of requests a user can make to an API within a given time window.', constraints: ['Low latency', 'Distributed state', 'Accurate counting'], examples: [{ input: '100 requests per minute', output: '429 Too Many Requests if exceeded' }] },
  { id: 'sd-9', topic: 'system_design', difficulty: 'Hard', title: 'Design Dropbox/Google Drive', statement: 'Design a cloud storage system that allows users to upload, download, and sync files across devices.', constraints: ['Data consistency', 'Block-level sync', 'Delta encoding'], examples: [{ input: 'File change on PC', output: 'Synced to Phone automatically' }] },
  { id: 'sd-10', topic: 'system_design', difficulty: 'Hard', title: 'Design Ticketmaster', statement: 'Design an online ticketing system for high-demand events where thousands of people try to buy tickets simultaneously.', constraints: ['Concurrency handling', 'Database locking', 'Scalability'], examples: [{ input: 'Concert sale starts', output: 'Tickets allocated without double-booking' }] },
  { id: 'sd-11', topic: 'system_design', difficulty: 'Hard', title: 'Design Distributed Cache', statement: 'Design a system like Redis or Memcached that provides low-latency key-value storage across a cluster of machines.', constraints: ['Consistency vs Availability', 'Eviction policies (LRU)', 'Partitioning'], examples: [{ input: 'Set key=val', output: 'Get key returns val from any node' }] },
  { id: 'sd-12', topic: 'system_design', difficulty: 'Hard', title: 'Design Payment System (Stripe/PayPal)', statement: 'Design a secure and reliable payment processing system that handles transactions, refunds, and payouts.', constraints: ['PCI compliance', 'IDEMPOTENCY', 'Auditing'], examples: [{ input: 'User pays $50', output: 'Merchant credited, User debited exactly once' }] },
  { id: 'sd-13', topic: 'system_design', difficulty: 'Hard', title: 'Design Google Search (Typeahead)', statement: 'Design the autocomplete feature for a search engine that suggests queries as the user types.', constraints: ['Millisecond latency', 'Frequent updates', 'Top-k suggestions'], examples: [{ input: 'User types "sys"', output: 'Suggestions: system design, sysadmin, etc.' }] },
  { id: 'sd-14', topic: 'system_design', difficulty: 'Hard', title: 'Design Notification Service', statement: 'Design a system that can send millions of notifications (Push, SMS, Email) to users based on various triggers.', constraints: ['Delivery guarantees', 'Prioritization', 'Provider abstraction'], examples: [{ input: 'Order shipped', output: 'Push + Email sent' }] },
  { id: 'sd-15', topic: 'system_design', difficulty: 'Hard', title: 'Design E-commerce Site (Amazon)', statement: 'Design a platform for shopping, including product catalog, search, shopping cart, and order management.', constraints: ['High availability for catalog', 'Strong consistency for orders', 'Inventory management'], examples: [{ input: 'Place order', output: 'Inventory decremented, Order confirmed' }] }
];

// Fill up to 100 questions with variations if needed - for now I have listed 100 distinct common ones.
// Total: 30 (arr) + 30 (dp) + 25 (tg) + 15 (sd) = 100.

const dataDir = path.join(__dirname, '..', 'backend', 'data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir);

fs.writeFileSync(
  path.join(dataDir, 'questions.json'),
  JSON.stringify(questions, null, 2)
);

console.log('Successfully seeded 100 questions to backend/data/questions.json');
